### PR TITLE
Updates for gateway 0.10.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by bvmensvoort** [comment]
Thanks!

**Comment by mrstegeman** [comment]
Thanks for merging! Would you mind building a new release when you get a chance?

**Comment by bvmensvoort** [comment]
I did a few cosmetic changes and created a release. Please let me know if anything else is needed.
Good to stay updated for the gateway.

**Comment by mrstegeman** [comment]
Thanks! The new release has been pushed to the add-on list.

**Pull request merged**
